### PR TITLE
Check if player can exit vehicle

### PR DESCRIPTION
**Pull request by Stanstar22**
Hook does not run off this function from my testing. If it does, then it's not running the hooks I want. So this will actually check if the player can exit the vehicle.

### CODE REVIEW

**Comment by Gredwitch** [comment]
Maybe you should use lfsGetPlane instead of GetVehicle

**Comment by Stanstar22** [comment]
Does this function not return the main entity of the vehicle though and not the prisoner pod which is the actual vehicle the player is in?

**Comment by Gredwitch** [comment]
Yea, but that way the player won't exit the vehicle if he isn't in an LFS plane when he presses the "exit vehicle" key he bound in the LFS controls (like it does currently)

**Comment by Blu-x92** [comment]
https://github.com/Blu-x92/LunasFlightSchool/commit/cabe7fcad00e58d6b6898e54b23c40e535738cf5

**Pull request closed without merging**
